cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'bash-completion'
brew 'coreutils'
brew 'docker'
brew 'fzf'
brew 'git'
brew 'go'
brew 'grc'
brew 'jp2a'
brew 'jq'
brew 'libgit2'
brew 'openssl'
brew 'postgresql'
brew 'python'
brew 'reattach-to-user-namespace'
brew 'shpotify'
brew 'spaceman-diff'
brew 'speedtest-cli'
brew 'tmux'
brew 'unrar'
brew 'watch'
brew 'wget'

cask 'iterm2'
cask 'slack'
cask 'spotify'
cask 'transmission' 
cask 'visual-studio-code'
